// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: grpc/p2p.proto

package ping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MSG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Order int32 `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *MSG) Reset() {
	*x = MSG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_p2p_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MSG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSG) ProtoMessage() {}

func (x *MSG) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_p2p_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSG.ProtoReflect.Descriptor instead.
func (*MSG) Descriptor() ([]byte, []int) {
	return file_grpc_p2p_proto_rawDescGZIP(), []int{0}
}

func (x *MSG) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MSG) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_p2p_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_p2p_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_grpc_p2p_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_grpc_p2p_proto protoreflect.FileDescriptor

var file_grpc_p2p_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x32, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x70, 0x32, 0x70, 0x22, 0x2b, 0x0a, 0x03, 0x4d, 0x53, 0x47, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x22, 0x19, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x2a, 0x0a,
	0x04, 0x52, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x08, 0x48, 0x61, 0x6e, 0x64, 0x4e, 0x65, 0x78,
	0x74, 0x12, 0x08, 0x2e, 0x70, 0x32, 0x70, 0x2e, 0x4d, 0x53, 0x47, 0x1a, 0x0a, 0x2e, 0x70, 0x32,
	0x70, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x68, 0x74, 0x74,
	0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4e, 0x61, 0x64, 0x64, 0x69, 0x4e, 0x61, 0x64, 0x6a, 0x61, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x2d,
	0x74, 0x6f, 0x2d, 0x70, 0x65, 0x65, 0x72, 0x3b, 0x70, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_p2p_proto_rawDescOnce sync.Once
	file_grpc_p2p_proto_rawDescData = file_grpc_p2p_proto_rawDesc
)

func file_grpc_p2p_proto_rawDescGZIP() []byte {
	file_grpc_p2p_proto_rawDescOnce.Do(func() {
		file_grpc_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_p2p_proto_rawDescData)
	})
	return file_grpc_p2p_proto_rawDescData
}

var file_grpc_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_p2p_proto_goTypes = []interface{}{
	(*MSG)(nil),   // 0: p2p.MSG
	(*Reply)(nil), // 1: p2p.Reply
}
var file_grpc_p2p_proto_depIdxs = []int32{
	0, // 0: p2p.Ring.HandNext:input_type -> p2p.MSG
	1, // 1: p2p.Ring.HandNext:output_type -> p2p.Reply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_p2p_proto_init() }
func file_grpc_p2p_proto_init() {
	if File_grpc_p2p_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_p2p_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MSG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_p2p_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_p2p_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_p2p_proto_goTypes,
		DependencyIndexes: file_grpc_p2p_proto_depIdxs,
		MessageInfos:      file_grpc_p2p_proto_msgTypes,
	}.Build()
	File_grpc_p2p_proto = out.File
	file_grpc_p2p_proto_rawDesc = nil
	file_grpc_p2p_proto_goTypes = nil
	file_grpc_p2p_proto_depIdxs = nil
}
